In [1]:
pip install pandas numpy pdfplumber openpyxl

Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\Users\YT\anaconda3\envs\corporate-pm\Lib\site-packages (2.4.3)
Collecting pdfplumber
  Downloading pdfplumber-0.11.9-py3-none-any.whl.metadata (43 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\YT\anaconda3\envs\corporate-pm\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting pdfminer.six==20251230 (from pdfplumber)
  Downloading pdfminer_six-20251230-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=9.1 (from pdfplumber)
  Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.6.0-py3-none-win_amd64.whl.metadata (68 kB)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\Users\YT\anaconda3\envs\corporate-pm\Lib\site-packages (from pdfminer.six==20251230->pdfplumber) (3.4.5)
Collecting cryptography>=36.0.0 (from pdfminer.six==20251230->pdfplumber)
  Downloading cryptography-46.0.7-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting cffi>=2.0.0 (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber)
  Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: six>=1.5 in c:\Users\YT\anaconda3\envs\corporate-pm\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.9 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.9 MB 1.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.9 MB 1.0 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.9 MB 818.6 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.9 MB 818.6 kB/s eta 0:00:11
   ------ --------------------------------- 1.6/9.9 MB 762.5 kB/s eta 0:00:11
   ------ --------------------------------- 1.6/9.9 MB 762.5 kB/s eta 0:00:11
   ------- -------------------------------- 1.8/9.9 MB 740.2 kB/s eta 0:00:11
   ------- -------------------------------- 1.8/9.9 MB 740.2 kB/s eta 0:00:11
   -------- ------------------------------- 2.1/9.9 MB 752.7 kB/s eta 0:00:11
   --------- ------------------------------ 2.4/9.9 MB 754.1 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/9.9 MB 754.1 kB/s eta 0:00:10
   ---------- ----------------------------- 2.6/9.9 MB 770.3 kB/s eta 0:00:10
   ---------- ----------------------------- 2.6/9.9 MB 770.3 kB/s eta 0:00:10
   ---------- ----------------------------- 2.6/9.9 MB 770.3 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/9.9 MB 702.0 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/9.9 MB 702.0 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/9.9 MB 702.0 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/9.9 MB 702.0 kB/s eta 0:00:10
   ------------ --------------------------- 3.1/9.9 MB 613.1 kB/s eta 0:00:12
   ------------ --------------------------- 3.1/9.9 MB 613.1 kB/s eta 0:00:12
   ------------ --------------------------- 3.1/9.9 MB 613.1 kB/s eta 0:00:12
   ------------- -------------------------- 3.4/9.9 MB 590.4 kB/s eta 0:00:11
   ------------- -------------------------- 3.4/9.9 MB 590.4 kB/s eta 0:00:11
   ------------- -------------------------- 3.4/9.9 MB 590.4 kB/s eta 0:00:11
   -------------- ------------------------- 3.7/9.9 MB 584.7 kB/s eta 0:00:11
   --------------- ------------------------ 3.9/9.9 MB 587.2 kB/s eta 0:00:11
   --------------- ------------------------ 3.9/9.9 MB 587.2 kB/s eta 0:00:11
   ---------------- ----------------------- 4.2/9.9 MB 593.5 kB/s eta 0:00:10
   ---------------- ----------------------- 4.2/9.9 MB 593.5 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.9 MB 603.2 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.9 MB 603.2 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.9 MB 603.2 kB/s eta 0:00:10
   ------------------- -------------------- 4.7/9.9 MB 585.7 kB/s eta 0:00:09
   ------------------- -------------------- 4.7/9.9 MB 585.7 kB/s eta 0:00:09
   -------------------- ------------------- 5.0/9.9 MB 584.1 kB/s eta 0:00:09
   -------------------- ------------------- 5.0/9.9 MB 584.1 kB/s eta 0:00:09
   --------------------- ------------------ 5.2/9.9 MB 581.7 kB/s eta 0:00:09
   --------------------- ------------------ 5.2/9.9 MB 581.7 kB/s eta 0:00:09
   ---------------------- ----------------- 5.5/9.9 MB 583.6 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/9.9 MB 583.6 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.9 MB 588.2 kB/s eta 0:00:08
   ----------------------- ---------------- 5.8/9.9 MB 588.2 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.9 MB 588.7 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 588.7 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 588.7 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/9.9 MB 584.6 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/9.9 MB 584.6 kB/s eta 0:00:07
   -------------------------- ------------- 6.6/9.9 MB 580.2 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/9.9 MB 580.2 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 581.7 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 581.7 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 581.7 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 581.7 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 581.7 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/9.9 MB 548.7 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/9.9 MB 548.7 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/9.9 MB 548.7 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/9.9 MB 548.7 kB/s eta 0:00:06
   ----------------------------- ---------- 7.3/9.9 MB 538.6 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/9.9 MB 538.6 kB/s eta 0:00:05
   ------------------------------ --------- 7.6/9.9 MB 536.9 kB/s eta 0:00:05
   ------------------------------ --------- 7.6/9.9 MB 536.9 kB/s eta 0:00:05
   ------------------------------- -------- 7.9/9.9 MB 538.2 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/9.9 MB 538.2 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/9.9 MB 538.2 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 537.1 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 503.0 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/9.9 MB 503.0 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/9.9 MB 503.0 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/9.9 MB 503.0 kB/s eta 0:00:03
   --------------------------------- ------ 8.4/9.9 MB 503.0 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 488.1 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 488.1 kB/s eta 0:00:03
   ---------------------------------- ----- 8.7/9.9 MB 488.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.9 MB 486.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.9 MB 486.1 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 486.7 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 486.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 490.1 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 490.1 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 490.1 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 489.8 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 489.8 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 489.8 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 480.2 kB/s  0:00:20
Downloading pdfplumber-0.11.9-py3-none-any.whl (60 kB)
Downloading pdfminer_six-20251230-py3-none-any.whl (6.6 MB)
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.6 MB 409.6 kB/s eta 0:00:15
   --- ------------------------------------ 0.5/6.6 MB 409.6 kB/s eta 0:00:15
   --- ------------------------------------ 0.5/6.6 MB 409.6 kB/s eta 0:00:15
   ---- ----------------------------------- 0.8/6.6 MB 466.0 kB/s eta 0:00:13
   ---- ----------------------------------- 0.8/6.6 MB 466.0 kB/s eta 0:00:13
   ------ --------------------------------- 1.0/6.6 MB 508.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.0/6.6 MB 508.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.0/6.6 MB 508.7 kB/s eta 0:00:11
   ------ --------------------------------- 1.0/6.6 MB 508.7 kB/s eta 0:00:11
   ------- -------------------------------- 1.3/6.6 MB 438.7 kB/s eta 0:00:13
   ------- -------------------------------- 1.3/6.6 MB 438.7 kB/s eta 0:00:13
   --------- ------------------------------ 1.6/6.6 MB 439.2 kB/s eta 0:00:12
   --------- ------------------------------ 1.6/6.6 MB 439.2 kB/s eta 0:00:12
   --------- ------------------------------ 1.6/6.6 MB 439.2 kB/s eta 0:00:12
   ----------- ---------------------------- 1.8/6.6 MB 453.5 kB/s eta 0:00:11
   ----------- ---------------------------- 1.8/6.6 MB 453.5 kB/s eta 0:00:11
   ------------ --------------------------- 2.1/6.6 MB 473.6 kB/s eta 0:00:10
   -------------- ------------------------- 2.4/6.6 MB 495.3 kB/s eta 0:00:09
   -------------- ------------------------- 2.4/6.6 MB 495.3 kB/s eta 0:00:09
   --------------- ------------------------ 2.6/6.6 MB 515.4 kB/s eta 0:00:08
   ----------------- ---------------------- 2.9/6.6 MB 537.7 kB/s eta 0:00:07
   ----------------- ---------------------- 2.9/6.6 MB 537.7 kB/s eta 0:00:07
   ------------------- -------------------- 3.1/6.6 MB 557.6 kB/s eta 0:00:07
   -------------------- ------------------- 3.4/6.6 MB 578.6 kB/s eta 0:00:06
   -------------------- ------------------- 3.4/6.6 MB 578.6 kB/s eta 0:00:06
   ---------------------- ----------------- 3.7/6.6 MB 592.7 kB/s eta 0:00:05
   ---------------------- ----------------- 3.7/6.6 MB 592.7 kB/s eta 0:00:05
   ---------------------- ----------------- 3.7/6.6 MB 592.7 kB/s eta 0:00:05
   ---------------------- ----------------- 3.7/6.6 MB 592.7 kB/s eta 0:00:05
   ---------------------- ----------------- 3.7/6.6 MB 592.7 kB/s eta 0:00:05
   ---------------------- ----------------- 3.7/6.6 MB 592.7 kB/s eta 0:00:05
   ----------------------- ---------------- 3.9/6.6 MB 526.7 kB/s eta 0:00:06
   ----------------------- ---------------- 3.9/6.6 MB 526.7 kB/s eta 0:00:06
   ------------------------- -------------- 4.2/6.6 MB 516.8 kB/s eta 0:00:05
   ------------------------- -------------- 4.2/6.6 MB 516.8 kB/s eta 0:00:05
   ------------------------- -------------- 4.2/6.6 MB 516.8 kB/s eta 0:00:05
   --------------------------- ------------ 4.5/6.6 MB 517.2 kB/s eta 0:00:05
   --------------------------- ------------ 4.5/6.6 MB 517.2 kB/s eta 0:00:05
   ---------------------------- ----------- 4.7/6.6 MB 522.4 kB/s eta 0:00:04
   ---------------------------- ----------- 4.7/6.6 MB 522.4 kB/s eta 0:00:04
   ------------------------------ --------- 5.0/6.6 MB 531.7 kB/s eta 0:00:04
   ------------------------------- -------- 5.2/6.6 MB 540.3 kB/s eta 0:00:03
   ------------------------------- -------- 5.2/6.6 MB 540.3 kB/s eta 0:00:03
   --------------------------------- ------ 5.5/6.6 MB 550.1 kB/s eta 0:00:02
   --------------------------------- ------ 5.5/6.6 MB 550.1 kB/s eta 0:00:02
   --------------------------------- ------ 5.5/6.6 MB 550.1 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ---------------------------------- ----- 5.8/6.6 MB 540.4 kB/s eta 0:00:02
   ------------------------------------ --- 6.0/6.6 MB 491.5 kB/s eta 0:00:02
   ------------------------------------ --- 6.0/6.6 MB 491.5 kB/s eta 0:00:02
   ------------------------------------ --- 6.0/6.6 MB 491.5 kB/s eta 0:00:02
   ------------------------------------ --- 6.0/6.6 MB 491.5 kB/s eta 0:00:02
   -------------------------------------- - 6.3/6.6 MB 483.6 kB/s eta 0:00:01
   -------------------------------------- - 6.3/6.6 MB 483.6 kB/s eta 0:00:01
   ---------------------------------------  6.6/6.6 MB 483.4 kB/s eta 0:00:01
   ---------------------------------------- 6.6/6.6 MB 482.9 kB/s  0:00:14
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading cryptography-46.0.7-cp311-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.5 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.5 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.5 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.5 MB ? eta -:--:--
   ------ --------------------------------- 0.5/3.5 MB 289.3 kB/s eta 0:00:11
   ------ --------------------------------- 0.5/3.5 MB 289.3 kB/s eta 0:00:11
   ------ --------------------------------- 0.5/3.5 MB 289.3 kB/s eta 0:00:11
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.5 MB 349.5 kB/s eta 0:00:08
   ------------ --------------------------- 1.0/3.5 MB 153.4 kB/s eta 0:00:16
   ------------ --------------------------- 1.0/3.5 MB 153.4 kB/s eta 0:00:16
   ------------ --------------------------- 1.0/3.5 MB 153.4 kB/s eta 0:00:16
   --------------- ------------------------ 1.3/3.5 MB 180.9 kB/s eta 0:00:13
   --------------- ------------------------ 1.3/3.5 MB 180.9 kB/s eta 0:00:13
   ------------------ --------------------- 1.6/3.5 MB 210.8 kB/s eta 0:00:10
   --------------------- ------------------ 1.8/3.5 MB 240.8 kB/s eta 0:00:07
   --------------------- ------------------ 1.8/3.5 MB 240.8 kB/s eta 0:00:07
   ------------------------ --------------- 2.1/3.5 MB 268.2 kB/s eta 0:00:06
   ------------------------ --------------- 2.1/3.5 MB 268.2 kB/s eta 0:00:06
   ------------------------ --------------- 2.1/3.5 MB 268.2 kB/s eta 0:00:06
   ------------------------ --------------- 2.1/3.5 MB 268.2 kB/s eta 0:00:06
   ------------------------ --------------- 2.1/3.5 MB 268.2 kB/s eta 0:00:06
   --------------------------- ------------ 2.4/3.5 MB 263.2 kB/s eta 0:00:05
   --------------------------- ------------ 2.4/3.5 MB 263.2 kB/s eta 0:00:05
   ------------------------------ --------- 2.6/3.5 MB 283.8 kB/s eta 0:00:04
   --------------------------------- ------ 2.9/3.5 MB 305.1 kB/s eta 0:00:02
   ------------------------------------ --- 3.1/3.5 MB 327.8 kB/s eta 0:00:02
   ---------------------------------------- 3.5/3.5 MB 356.6 kB/s  0:00:11
Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl (182 kB)
Downloading pillow-12.2.0-cp311-cp311-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.1 MB 577.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.1 MB 577.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.1 MB 577.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.1 MB 577.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.1 MB 577.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.1 MB 577.4 kB/s eta 0:00:12

In [4]:
import pandas as pd
import numpy as np

# File paths
wb_file = r"data\all.xlsx"
mospi_pdf1 = r"data\30.pdf"
mospi_pdf2 = r"data\QPISR_4th_QTR_2024-25.pdf"

# Load World Bank Excel
wb_df = pd.read_excel(wb_file, sheet_name=0, header=1)

print(wb_df.columns.tolist())
wb_df.head()

c:\Users\YT\anaconda3\envs\corporate-pm\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['Project ID', 'Region', 'Country', 'Project Status', 'Last Stage Reached Name', 'Project Name', 'Project Development Objective ', 'Implementing Agency', 'Public Disclosure Date', 'Board Approval Date', 'Loan Effective Date', 'Project Closing Date', 'Current Project Cost', 'IBRD Commitment', 'IDA Commitment', 'Grant Amount', 'Total IBRD, IDA and Grant Commitment', 'Borrower', 'Lending Instrument', 'Environmental Assessment Category', 'Environmental and Social Risk', 'Associated Project', 'Consultant Services Required', 'Last Update Date', 'Financing Type']

,Project ID,Region,Country,Project Status,Last Stage Reached Name,Project Name,Project Development Objective,Implementing Agency,Public Disclosure Date,Board Approval Date,...,Grant Amount,"Total IBRD, IDA and Grant Commitment",Borrower,Lending Instrument,Environmental Assessment Category,Environmental and Social Risk,Associated Project,Consultant Services Required,Last Update Date,Financing Type
0,id,regionname,countryshortname,status,last_stage_reached_name,project_name,pdo,impagency,public_disclosure_date,boardapprovaldate,...,grantamt,curr_total_commitment,borrower,lendinginstr,envassesmentcategorycode,esrc_ovrl_risk_rate,supplementprojectflg,cons_serv_reqd_ind,proj_last_upd_date,projectfinancialtype
1,P000001,Africa,Africa,Closed,Bank Approved,West Africa Pilot Community-based Natural Reso...,CONSERVATION OF BIO-DIVERSITY. OBJECTIVE IS T...,NaN,1995-09-14,1995-09-14T00:00:00Z,...,11400000,11400000,NaN,Specific Investment Loan,B,Not Applicable,N,NaN,2013-01-15,Other
2,P000002,Africa,Africa,Dropped,Bank Approved,LAKE VICTORIA ENVIRO,NaN,NaN,NaN,1997-06-30T00:00:00Z,...,NaN,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN
3,P000003,Africa,Africa,Closed,Bank Approved,REIMP(CEN.ENV.INFO),REIMP TO IMPROVE/STRENGTHEN PLANNING & MNGT. O...,NaN,1997-12-18,1997-12-18T00:00:00Z,...,16700000,16700000,NaN,Specific Investment Loan,C,Not Applicable,N,NaN,2013-01-15,Other
4,P000004,Africa,Africa,Dropped,Bank Approved,P.TA/SADCC TRADE DEV,NaN,NaN,NaN,1991-06-30T00:00:00Z,...,NaN,NaN,NaN,Specific Investment Loan,C,Not Applicable,NaN,NaN,NaN,NaN

In [7]:
for col in wb_df.columns:
    print(f"'{col}'")

'Project ID'
'Region'
'Country'
'Project Status'
'Last Stage Reached Name'
'Project Name'
'Project Development Objective '
'Implementing Agency'
'Public Disclosure Date'
'Board Approval Date'
'Loan Effective Date'
'Project Closing Date'
'Current Project Cost'
'IBRD Commitment'
'IDA Commitment'
'Grant Amount'
'Total IBRD, IDA and Grant Commitment'
'Borrower'
'Lending Instrument'
'Environmental Assessment Category'
'Environmental and Social Risk'
'Associated Project'
'Consultant Services Required'
'Last Update Date'
'Financing Type'

In [8]:
wb_df.columns = (
    wb_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [10]:
# Convert dates
wb_df['board_approval_date'] = pd.to_datetime(wb_df['board_approval_date'], errors='coerce')
wb_df['project_closing_date'] = pd.to_datetime(wb_df['project_closing_date'], errors='coerce')

# Drop missing
# Convert both to datetime and REMOVE timezone
wb_df['board_approval_date'] = pd.to_datetime(
    wb_df['board_approval_date'], errors='coerce'
).dt.tz_localize(None)

wb_df['project_closing_date'] = pd.to_datetime(
    wb_df['project_closing_date'], errors='coerce'
).dt.tz_localize(None)
# Convert cost
wb_df['current_project_cost'] = pd.to_numeric(wb_df['current_project_cost'], errors='coerce')

# Log transform
wb_df['log_project_cost'] = np.log1p(wb_df['current_project_cost'])

# Risk mapping
risk_map = {'Low':1, 'Moderate':2, 'Substantial':3, 'High':4}
wb_df['risk_rating'] = wb_df['environmental_and_social_risk'].map(risk_map)

wb_df.head()

,project_id,region,country,project_status,last_stage_reached_name,project_name,project_development_objective,implementing_agency,public_disclosure_date,board_approval_date,...,borrower,lending_instrument,environmental_assessment_category,environmental_and_social_risk,associated_project,consultant_services_required,last_update_date,financing_type,log_project_cost,risk_rating
1,P000001,Africa,Africa,Closed,Bank Approved,West Africa Pilot Community-based Natural Reso...,CONSERVATION OF BIO-DIVERSITY. OBJECTIVE IS T...,NaN,1995-09-14,1995-09-14,...,NaN,Specific Investment Loan,B,Not Applicable,N,NaN,2013-01-15,Other,16.394970,NaN
3,P000003,Africa,Africa,Closed,Bank Approved,REIMP(CEN.ENV.INFO),REIMP TO IMPROVE/STRENGTHEN PLANNING & MNGT. O...,NaN,1997-12-18,1997-12-18,...,NaN,Specific Investment Loan,C,Not Applicable,N,NaN,2013-01-15,Other,16.630919,NaN
17,P000017,Africa,Africa,Closed,Bank Approved,3A-TG/BN Engineering TAL (FY92),I) INSTITUTIONAL STRENGTHENING; II) A LEAST-CO...,NaN,1992-05-19,1992-05-19,...,NaN,Technical Assistance Loan,C,Not Applicable,N,NaN,2013-01-15,IDA,15.623799,NaN
34,P000034,Eastern and Southern Africa,Angola,Closed,Bank Approved,INFRASTRUCTURE REHAB,"Feasibility and engineering studies, technical...",NaN,1991-07-16,1991-07-16,...,NaN,Technical Assistance Loan,C,Not Applicable,N,NaN,2021-03-11,IDA,16.959663,NaN
35,P000035,Eastern and Southern Africa,Angola,Closed,Bank Approved,LOBITO/BENG.REHAB.,"PROJECT WOULD ASSIST GOVT TO I) RESTORE WATER,...",NaN,1992-01-07,1992-01-07,...,NaN,Sector Investment and Maintenance Loan,C,Not Applicable,N,NaN,2013-01-15,IDA,18.002130,NaN

In [11]:
# Drop missing
wb_df = wb_df.dropna(subset=['board_approval_date', 'project_closing_date'])

# Create duration
wb_df['actual_duration_days'] = (
    wb_df['project_closing_date'] - wb_df['board_approval_date']
).dt.days

In [12]:
import pdfplumber
import pandas as pd

def extract_tables(pdf_path):
    all_tables = []
    
    with pdfplumber.open(pdf_path) as pdf:
        for i, page in enumerate(pdf.pages):
            tables = page.extract_tables()
            
            for table in tables:
                df = pd.DataFrame(table)
                all_tables.append(df)
    
    return all_tables

# Extract both PDFs
tables_1 = extract_tables(mospi_pdf1)
tables_2 = extract_tables(mospi_pdf2)

print("Tables in PDF1:", len(tables_1))
print("Tables in PDF2:", len(tables_2))

Tables in PDF1: 328
Tables in PDF2: 280

In [13]:
tables_1[0].head()

                                                   0
0  484\nFEBRUARY 2026\nScan the QR code to access...
1  Project Assessment, Infrastructure Monitoring ...

In [14]:
mospi_df = tables_1[0].copy()

# Set first row as header
mospi_df.columns = mospi_df.iloc[0]
mospi_df = mospi_df[1:]

mospi_df.head()

0 484\nFEBRUARY 2026\nScan the QR code to access\nthe PAIMANA Portal.
1  Project Assessment, Infrastructure Monitoring ...

In [15]:
mospi_df.columns = mospi_df.columns.str.strip().str.lower().str.replace(" ", "_")

In [16]:
print(mospi_df.columns.tolist())

['484\nfebruary_2026\nscan_the_qr_code_to_access\nthe_paimana_portal.']

In [17]:
for i, table in enumerate(tables_2):
    print(f"\nTable {i}")
    print(pd.DataFrame(table).head())

Table 0
  0         1
0    SYNOPSIS

Table 1
  0
0
1
2

Table 2
  0               1
0    LIST OF TABLES

Table 3
         0                               1         2  \
0  Sl. No.                          Sector  Projects
1        1                  CIVIL AVIATION        41
2        2                            COAL       121
3        3  DEPARTMENT OF HIGHER EDUCATION        20
4        4                           DONER         1

                                                   3  \
0  Cost\nOriginal\n(Revised)*\n{Anticipated}\nin ...
1                28,200.17\n(29,343.52)\n{32,097.25}
2             208,420.76\n(212,921.45)\n{218,842.29}
3                 9,680.92\n(10,072.78)\n{10,127.07}
4                         151.33\n(151.33)\n{151.33}

                                       4
0  Cumulative\nExpenditure\nin Rs. Crore
1                              18,637.74
2                              76,381.85
3                               7,619.19
4                                 148.33

Table 4
         0                   1         2  \
0  Sl. No.              Sector  Projects
1       17  TELECOMMUNICATIONS         6
2       18   URBAN DEVELOPMENT        27
3       19     WATER RESOURCES        35
4                        Total      1773

                                                   3  \
0  Cost\nOriginal\n(Revised)*\n{Anticipated}\nin ...
1                26,961.69\n(26,949.89)\n{26,949.89}
2             265,881.46\n(272,720.33)\n{286,578.30}
3                21,815.94\n(21,770.16)\n{68,489.21}
4              2672909.7\n(2929094.92)\n{3211901.18}

                                       4
0  Cumulative\nExpenditure\nin Rs. Crore
1                               9,132.74
2                            2,01,259.87
3                              31,509.48
4                             1778240.05

Table 5
         0                            1         2  \
0  Sl. No.                        State  Projects
1        1  ANDAMAN AND NICOBAR ISLANDS        10
2        2               ANDHRA PRADESH       108
3        3            ARUNACHAL PRADESH        23
4        4                        ASSAM        66

                                                   3  \
0  Cost Original\n(Revised)*\n{Anticipated}\nin R...
1                   2,956.02\n(3,029.18)\n{3,010.04}
2             148,221.66\n(158,401.99)\n{211,663.70}
3                48,922.12\n(48,985.65)\n{68,835.80}
4                66,847.55\n(67,246.06)\n{76,566.33}

                                       4
0  Cumulative\nExpenditure\nin Rs. Crore
1                               1,801.96
2                            1,30,080.10
3                              32,613.79
4                              49,338.28

Table 6
         0               1         2  \
0  Sl. No.           State  Projects
1       17  MADHYA PRADESH        64
2       18     MAHARASHTRA       192
3       19         MANIPUR        33
4       20       MEGHALAYA        15

                                                   3  \
0  Cost Original\n(Revised)*\n{Anticipated}\nin R...
1             108,150.99\n(114,357.67)\n{124,349.77}
2             240,215.06\n(244,750.37)\n{277,179.38}
3                15,746.25\n(23,602.31)\n{33,526.68}
4                   6,028.77\n(6,019.79)\n{5,974.15}

                                       4
0  Cumulative\nExpenditure\nin Rs. Crore
1                              43,146.30
2                            1,50,047.54
3                              19,646.09
4                               3,775.18

Table 7
         0            1         2  \
0  Sl. No.        State  Projects
1       33  WEST BENGAL        62
2                 Total      1773

                                                   3  \
0  Cost Original\n(Revised)*\n{Anticipated}\nin R...
1                67,640.76\n(72,494.42)\n{90,447.68}
2              2672909.7\n(2929094.92)\n{3211901.18}

                                       4
0  Cumulative\nExpenditure\nin Rs. Crore
1                              48,255.63
2                             1778240.05

Table 8
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1    COAL
2     NaN        1  DUDHICHUA EXPANSION OCP (10 TO 20 MTPA)\n(NCL)...
3     NaN        2  MADHUBAND NLW WASHERY\n(BCCL)\n(N06000126)\n(J...
4   DONER

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1
2                       1255.17                                     03-2022
3                        289.45                                     05-2014
4

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1
2                                1254.21
3                                 300.01
4

Table 9
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1               11  INSTALLATION OF STANDBY SRU TRAIN OF 525 TPD\n...
2     NaN       12  CGD PROJECT AT KANYAKUMARI, TUTICORIN, TIRUNVE...
3     NaN       13  DEVELOPMENT PLAN OF CBM - BOKARO BLOCK\n(ONGC)...
4     NaN       14  SWRO II WITH LLPH FACILITIES\n(HPCL)\n(N160003...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                         427.1                                     09-2022
2                          1295                                     03-2030
3                        823.27                                     03-2023
4                        196.26                                     07-2020

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 312.13
2                                 145.61
3                                1067.89
4                                 196.26

Table 10
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       21  DELHI-VADODARA GREENFIELD ALIGNMENT (NH-148N)\...
2     NaN       22  CONSTRUCTION OF TWO LANE WITH HARD SHOULDERS\n...
3     NaN       23  CONSTRUCTION OF 8 LANE DWARKA EXPRESSWAY (NH-\...
4     NaN       24  4-LANING OF ITANAGAR TO BANDARDEWA SECTION OF ...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                       1425.02                                     03-2023
2                        285.68                                     09-2022
3                        1484.3                                     12-2020
4                         437.6                                     03-2027

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                1420.03
2                                  193.9
3                                1376.15
4                                 366.59

Table 11
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       30  4L OF SUHAGADI TO BARDIYA AMRA FROM KM. 89.200...
2     NaN       31  IMPHAL ? MOREH PACKAGE- 3\n(NHIDCL)\n(N2400135...
3     NaN       32  2L+PS OF THIKRI ANJAD SECTION OF NH-347B\n(MoR...
4     NaN       33  FOUR LANNING OF RAMPUR- KATHGODAM SECTION OF\n...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                        823.05                                     10-2024
2                        259.31                                     12-2022
3                        249.05                                     07-2018
4                           899                                     04-2019

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 402.85
2                                 144.94
3                                 221.19
4                                 1143.5

Table 12
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       39  CONSTRUCTION OF ROB AND ITS APPROACHES IN LIEU...
2     NaN       40  CONSTRUCTION OF TWO LANE WITH PAVED SHOULDERS\...
3     NaN       41  CONSTRUCTION OF 2 LANE ROAD OF POTIN TO PANGIN...
4     NaN       42  DELHI-VADODARA GREENFIELD ALIGNMENT (NH-148N)\...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                        160.27                                     09-2023
2                        167.28                                     04-2022
3                        543.05                                     03-2027
4                       1341.36                                     12-2023

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 174.36
2                                  145.2
3                                 588.85
4                                1089.73

Table 13
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       47  6L FLYOVER AT BORAGAON, GORCHUK, LOKHRA AND\nB...
2     NaN       48  DWARKA EXPRESSWAY PKG-III (DELHI/HR BORDER TO\...
3     NaN       49  WIDENING/IMPROVEMENT TO 4-LANE WITH PAVED\nSHO...
4     NaN       50  CONSTRUCTION OF 2 LANE ROAD OF POTIN TO PANGIN...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                           300                                     08-2024
2                          2228                                     11-2020
3                        208.84                                     04-2022
4                         486.7                                     03-2027

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 439.65
2                                 1628.6
3                                 193.59
4                                 480.44

Table 14
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1               56  MULAKALACHERUVU TO MADANAPALLE SECTION OF NH42...
2     NaN       57  CONSTRUCTION OF NEW 4-LANE BRIDGE ACROSS\nVARS...
3     NaN
4     NaN       58  SEWERAGE SYSTEM WITH SEWER NETWORK PATNA\nBEUR...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                         480.1                                     12-2024
2                        247.02                                     03-2020
3
4                        225.77                                     03-2020

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 443.87
2                                  93.29
3
4                                 363.79

Table 15
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       66  INTERCEPTION AND DIVERSION WORKS WITH STP AT\n...
2     NaN       67  SEWERAGE SYSTEM AND STP WORKS AT HALISHAHR\n(K...
3     NaN       68  INTERCEPTION AND DIVERSION WORKS WITH STP AT\n...
4     NaN       69  CONSTRUCTION OF 318 MLD WWTP WITH 10 YEARS O A...

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                        298.12                                     07-2021
2                        274.76                                     12-2019
3                        271.39                                     08-2021
4                        515.07                                     01-2021

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 103.24
2                                 278.33
3                                 182.26
4                                 388.08

Table 16
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1               76  INTERCEPTION AND DIVERSION WORKS AND SEWAGE\nT...
2     NaN       77  MATHURA SEWERAGE SCHEME\n(UPJalNigam)\n(N30000...
3                                                               Total

                              3                                           4  \
0  Original\nCost\nin Rs. Crore  Date of Commissioning\nOriginal\n(MM/YYYY)
1                        206.05                                     10-2021
2                        460.45                                     12-2020
3                     81,046.73

                                       5
0  Cumulative\nExpenditure\nin Rs. Crore
1                                 140.22
2                                  315.3
3                              80,175.01

Table 17
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1    COAL        1  RPR OF HINGULA EXPANSION OCP\n(MCL)\n(N0600028...
2     NaN        2  BHUBANESWARI EXPANSION OCP\n(MCL)\n(N06000286)...
3     NaN        3  BLOCK-E OCP (15 MTY)\n(BCCL)\n(N06000287)\n(JH...
4     NaN        4       BALABHADRA OCP\n(MCL)\n(N06000288)\n(ODISHA)

                               3  \
0  Date\nof\nApproval\n(MM/YYYY)
1                     1 1 - 2022
2                      3 - 2 024
3                         3-2024
4                         4-2023

                                                   4  \
0  Cost Original\n(Revised)\n{Anticipated}\nin Rs...
1                   1,561.85\n(1,561.85)\n{1,561.85}
2                   5,366.28\n(5,366.28)\n{5,366.28}
3                   5,850.83\n(5,850.83)\n{5,850.83}
4                         978.44\n(978.44)\n{978.44}

                                                   5
0  Date of Commissioning Original\n(Revised)\n{An...
1                           3/2029\n(N.A.)\n{3/2029}
2                           3/2031\n(N.A.)\n{3/2031}
3                           3/2029\n(N.A.)\n{3/2029}
4                           3/2030\n(N.A.)\n{3/2030}

Table 18
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       10  TRANSMISSION SYSTEM STRENGTHENING FOR\nINTERCO...
2     NaN       11  AUGMENTATION OF TRANSFORMATION CAPACITY AT JAM...
3     NaN       12  TRANSMISSION SYSTEM FOR EVACUATION OF POWER FR...
4     NaN       13  TRANSMISSION SYSTEM FOR EVACUATION OF POWER FR...

                               3  \
0  Date\nof\nApproval\n(MM/YYYY)
1                         8-2024
2                        10-2024
3                        10-2024
4                        10-2024

                                                   4  \
0  Cost Original\n(Revised)\n{Anticipated}\nin Rs...
1                   1,382.00\n(1,382.00)\n{1,382.00}
2                         329.00\n(329.00)\n{329.00}
3                   3,674.00\n(3,674.00)\n{3,674.00}
4                   4,766.00\n(4,766.00)\n{4,766.00}

                                                   5
0  Date of Commissioning Original\n(Revised)\n{An...
1                           8/2026\n(N.A.)\n{8/2026}
2                           7/2026\n(N.A.)\n{7/2026}
3                         10/2026\n(N.A.)\n{10/2026}
4                         10/2026\n(N.A.)\n{10/2026}

Table 19
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1               18  TRANSMISSION SYSTEM FOR EVACUATION OF POWER FR...
2     NaN       19  600 MW SOLAR POWER PROJECT UNDER CPSU SCHEME\n...
3     NaN       20  TWO LANING OF TRICHY - KARAIKUDI AND TRYCHI BY...
4     NaN       21  WIDENING AND STRENGTHENING OF RAFIABAD-KUPWARA...

                               3  \
0  Date\nof\nApproval\n(MM/YYYY)
1                        11-2024
2                    4 - 2 0 2 2
3                    5 - 2 0 1 0
4                         3-2024

                                                   4  \
0  Cost Original\n(Revised)\n{Anticipated}\nin Rs...
1                24,819.00\n(24,819.00)\n{24,819.00}
2                   4,100.45\n(4,100.45)\n{4,100.45}
3                         374.00\n(374.00)\n{166.90}
4                   1,404.94\n(1,404.94)\n{1,404.94}

                                                   5
0  Date of Commissioning Original\n(Revised)\n{An...
1                           5/2029\n(N.A.)\n{5/2029}
2                           3/2026\n(N.A.)\n{3/2026}
3                           5/2013\n(N.A.)\n{5/2013}
4                           5/2027\n(N.A.)\n{5/2027}

Table 20
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1     NaN       26  DEVELOPMENT OF SIX LANE ACCESS CONTROLLED GREE...
2     NaN       27  ACCESS CONTROLLED HIGHWAY OF 4 LANE WITH PAVED...
3     NaN       28  ACCESS CONTROLLED HIGHWAY OF 4 LANE WITH PAVED...
4     NaN       29  REHABILITATION AND UP GRADATION FROM 4 TO 8 LA...

                               3  \
0  Date\nof\nApproval\n(MM/YYYY)
1                         2-2023
2                        12-2024
3                        12-2024
4                         3-2024

                                                   4  \
0  Cost Original\n(Revised)\n{Anticipated}\nin Rs...
1                   1,092.18\n(1,092.18)\n{1,092.18}
2                   1,376.10\n(1,376.10)\n{1,376.10}
3                   1,346.82\n(1,346.82)\n{1,346.82}
4                         882.45\n(882.45)\n{882.45}

                                                   5
0  Date of Commissioning Original\n(Revised)\n{An...
1                           2/2027\n(N.A.)\n{2/2027}
2                         12/2026\n(N.A.)\n{12/2026}
3                         12/2026\n(N.A.)\n{12/2026}
4                         10/2026\n(N.A.)\n{10/2026}

Table 21
        0        1                                                  2  \
0  Sector  Sl. No.  Project Name\n(Agency Name)\n(Project Code)\n(...
1               34  PANGO TO JORGING ROAD PKG-1\n(NHIDCL)\n(N24002...
2     NaN       35  BILASIPURA- GUWAHATI ROAD PKG-1\n(NHIDCL)\n(N2...
3     NaN       36  SILCHAR-JIRIBAM PKG-1\n(NHIDCL)\n(N24002226)\n...
4     NaN       37  JESSAMI TO LAYNEN BRIDGE UKHRUL - JESSAMI PKG-...

                               3  \
0  Date\nof\nApproval\n(MM/YYYY)
1                       1 - 2024
2                     2 - 2 0 24
3                         1-2024
4                    3 - 2 0 2 3

                                                   4  \
0  Cost Original\n(Revised)\n{Anticipated}\nin Rs...
1                         898.19\n(898.19)\n{898.19}
2                   1,081.15\n(1,081.15)\n{1,081.15}
3                         957.95\n(957.95)\n{957.95}
4                         164.89\n(164.89)\n{164.89}

                                                   5
0  Date of Commissioning Original\n(Revised)\n{An...
1                           7/2027\n(N.A.)\n{7/2027}
2                           8/2027\n(N.A.)\n{8/2027}
3                           1/2028\n(N.A.)\n{1/2028}
4                           6/2026\n(N.A.)\n{6/2026}

Table 22